language: german
target: jekyll

# Link to home
url: /
destination: _output_de
github_editme_path: https://github.com/amzn/appstore-alexa-docs/
audio_path: docs_de/audio
image_path: docs_de

port: 4002
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs_de:
    output: true
  search_de:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav_de
  -
    scope:
      path: ""
      type: docs_de
    values:
      layout: default
      topnav: topnav_de
  -
    scope:
      path: ""
      type: search_de
    values:
      layout: default
      topnav: topnav_de
      toc: false
      github_button: false
      search: false

exclude:
  - Gemfile
  - Gemfile.lock
  - hippomenus/
  - output_ja
  - output_de
  - output_hippo
  - s3_deploy
  - _site
  - buildandpush.sh
  - _config*
  - jekyll*
  - s3_website.yml
  - docs/testmate/msword/
  - webapp
  - sapp


########## UI text ###############

uistring:
    tableofcontents: Inhaltsverzeichnis
    log_doc_issue: Log Doc Ausgabe
    breadcrumb:
      home: Zuhause
      documentation: Dokumentation
    expandall: Alle erweitern
    collapseall: Alle reduzieren
    title: Jekyll Dokumentation Theme # Displays as site title on top nav bar and on site metadata
    description: Dokumentationsthema f√ºr Jekyll-Webseiten # Displays as site description meta
    search_placeholder: Suche ...
    minitoc_title: Inhaltsverzeichnis
    github_edit_button_text: Bearbeiten Sie diese Seite
    search_results_page_title: Suchergebnisse
    search_placeholder_global: G Oba l Sayre rch ...
    search_placeholder_product: P Rodzu ct Sayre rch ...
    search_no_results_found: Keine Suchergebnisse gefunden.
    products: Products -- DE
    docindex_product: Produkte
    docindex_startpage: Startseite
